export type DribbleLanguage = 'en' | 'fr' | 'es' | 'de' | 'pt-BR';

export type TranslationParams = Readonly<Record<string, string | number>>;

export const languageStorageKey = 'basketball-frenzy-language';

export const supportedLanguages: readonly DribbleLanguage[] = ['de', 'en', 'es', 'fr', 'pt-BR'];

export const languageNames: Readonly<Record<DribbleLanguage, string>> = {
  en: 'English',
  fr: 'Français',
  es: 'Español',
  de: 'Deutsch',
  'pt-BR': 'Português (Brasil)',
};

const en = {
  'language.title': 'CHOOSE YOUR LANGUAGE',
  'language.subtitle': 'You can change this anytime in Settings',
  'name.welcome': 'WELCOME!',
  'name.subtitle': 'ENTER YOUR USERNAME TO GET STARTED',
  'name.placeholder': 'Enter username...',
  'name.confirm': 'Confirm',
  'name.error': 'Enter at least 2 characters.',
  'menu.play': 'Play',
  'menu.achievements': 'Achievements',
  'menu.tutorial': 'Tutorial',
  'menu.settings': 'Settings',
  'menu.shop': 'Shop',
  'menu.exit': 'Exit',
  'menu.back': 'Back',
  'menu.close': 'Close',
  'menu.reset': 'Reset Data',
  'profile.stars': 'STARS',
  'profile.courtLevel': 'COURT LEVEL',
  'profile.bestScores': 'BEST SCORES',
  'profile.normal': 'NORMAL',
  'profile.hard': 'HARD',
  'mode.chooseRun': 'CHOOSE YOUR RUN',
  'mode.title': 'Game Mode',
  'mode.normal': 'Normal Run',
  'mode.hard': 'Hard Endless',
  'mode.lastBounce': 'Last Bounce',
  'mode.multiplayer': 'Multiplayer',
  'mode.normalDetail': '3 LIVES · 2 MIN · FINAL SHOT',
  'mode.hardDetail': '2 LIVES · ENDLESS · SCORE x1.25',
  'mode.comingSoon': 'COMING SOON',
  'mode.online': 'ONLINE',
  'tutorial.choose': 'Choose Tutorial',
  'tutorial.classic': 'Classic',
  'tutorial.classicDetail': 'Targets, timing, health and Frenzy',
  'tutorial.versusAi': 'VERSUS AI',
  'tutorial.versusDetail': 'Risk Cards, returns and recovery gates',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.master': 'Master Volume',
  'settings.music': 'Music',
  'settings.sfx': 'Sound FX',
  'settings.motion': 'Reduced Motion',
  'settings.flashes': 'Reduced Flashes',
  'settings.contrast': 'High Contrast Targets',
  'settings.touchControls': 'Touch Controls',
  'settings.touchSplit': 'Split Tap',
  'settings.touchSwipe': 'Swipe Gestures',
  'settings.playerData': 'PLAYER DATA',
  'shop.title': 'Locker',
  'shop.complete': 'Collection complete',
  'shop.equipped': 'EQUIPPED',
  'shop.owned': 'OWNED',
  'shop.locked': 'LOCKED',
  'shop.equip': 'Equip',
  'shop.buy': 'Buy - {price} Stars',
  'achievements.career': 'CAREER PROGRESS',
  'achievements.completeCount': '{count} / {total} COMPLETE',
  'achievements.complete': 'COMPLETE',
  'achievements.locked': 'LOCKED',
  'achievements.daily': 'DAILY',
  'achievements.weekly': 'WEEKLY',
  'achievement.score10000.title': 'Five-Figure Run',
  'achievement.score10000.description': 'Score 10,000 points in one game.',
  'achievement.firstPurchase.title': 'First Purchase',
  'achievement.firstPurchase.description': 'Buy your first item from the shop.',
  'achievement.playTutorial.title': 'Training Day',
  'achievement.playTutorial.description': 'Complete the Classic and Last Bounce tutorials.',
  'achievement.starWithoutSwitching.title': 'Hold Your Ground',
  'achievement.starWithoutSwitching.description': 'Collect a star without switching lanes.',
  'achievement.highScore.title': 'High Score',
  'achievement.highScore.description': 'Complete your first run and set a personal best.',
  'challenge.scoreSprint.title': 'Score Sprint',
  'challenge.scoreSprint.description': 'Score 2,500 points in one run.',
  'challenge.hazardRun.title': 'Clean Court',
  'challenge.hazardRun.description': 'Avoid 15 hazards in one run.',
  'challenge.rallyMaster.title': 'Long Rally',
  'challenge.rallyMaster.description': 'Reach a 12-pass rally in Last Bounce.',
  'challenge.weekly.scoreSprint.title': 'Weekly Scorer',
  'challenge.weekly.scoreSprint.description': 'Score 5,000 points in one run.',
  'challenge.weekly.hazardRun.title': 'Defensive Wall',
  'challenge.weekly.hazardRun.description': 'Avoid 30 hazards in one run.',
  'challenge.weekly.rallyMaster.title': 'Rally Legend',
  'challenge.weekly.rallyMaster.description': 'Reach a 20-pass Last Bounce rally.',
  'hud.runObjectives': 'RUN OBJECTIVES',
  'hud.allObjectives': 'All objectives complete',
  'hud.timeLeft': 'TIME LEFT',
  'hud.finalShot': 'FINAL SHOT',
  'hud.runComplete': 'RUN COMPLETE',
  'hud.frenzy': 'FRENZY MODE',
  'hud.centerSwitch': 'CENTER SWITCH',
  'hud.scanning': 'SCANNING',
  'hud.training': 'TRAINING {current} / {total}',
  'hud.trainingComplete': 'TRAINING COMPLETE',
  'hud.exitTutorial': 'EXIT TUTORIAL',
  'objective.score-1200': 'Score 1,200',
  'objective.score-1800': 'Score 1,800',
  'objective.hit-15': 'Hit 15 Targets',
  'objective.perfect-4': '4 Perfect Switches',
  'objective.avoid-10': 'Clear 10 Hazards',
  'objective.combo-6': 'Reach Combo x6',
  'objective.survive-45': 'Survive 45s',
  'objective.star-1': 'Collect Frenzy Star',
  'objective.rounds-2': 'Win 2 Rounds',
  'objective.rally-8': '8-Pass Rally',
  'objective.returns-7': '7 Returns',
  'objective.risk-1': '1 Risk Pass',
  'objective.versus-45': 'Hold Rally 45s',
  'lesson.left-bounce.title': 'Power Bounce',
  'lesson.left-bounce.instruction': 'The ball starts on your left. Send it high above low hazards.',
  'lesson.left-bounce.control': 'LEFT CLICK',
  'lesson.switch-right.title': 'Switch Hands',
  'lesson.switch-right.instruction': 'Bounce through center and catch the ball with your right hand.',
  'lesson.switch-right.control': 'RIGHT CLICK',
  'lesson.right-bounce.title': 'Right Power Bounce',
  'lesson.right-bounce.instruction': 'With the ball on the right, launch another high bounce.',
  'lesson.right-bounce.control': 'RIGHT CLICK',
  'lesson.switch-left.title': 'Return Left',
  'lesson.switch-left.instruction': 'Switch back through the center lane.',
  'lesson.switch-left.control': 'LEFT CLICK',
  'lesson.score-target.title': 'Score Target',
  'lesson.score-target.instruction': 'Keep the ball bouncing on the left to collect the yellow target.',
  'lesson.score-target.control': 'HOLD YOUR LANE',
  'lesson.center-target.title': 'Center Timing',
  'lesson.center-target.instruction': 'Watch the bottom meter. Switch hands as its marker reaches the center.',
  'lesson.center-target.control': 'RIGHT CLICK ON BEAT',
  'lesson.avoid-hazard.title': 'Avoid Hazards',
  'lesson.avoid-hazard.instruction': 'The red target costs a life. Power-bounce over it and let it pass.',
  'lesson.avoid-hazard.control': 'HIGH BOUNCE',
  'lesson.health-target.title': 'Restore Health',
  'lesson.health-target.instruction': 'Collect the glowing cross to restore a missing heart.',
  'lesson.health-target.control': 'HOLD YOUR LANE',
  'lesson.bonus-star.title': 'Bonus Star',
  'lesson.bonus-star.instruction': 'Rare stars trigger Frenzy. Use a Power bounce to collect this one.',
  'lesson.bonus-star.control': 'HIGH BOUNCE',
  'lesson.frenzy.title': 'Frenzy Power',
  'lesson.frenzy.instruction': 'The star turned the ball gold. During Frenzy, every target is good.',
  'lesson.frenzy.control': 'HIT THE YELLOW TARGET',
  'lesson.versus-lives.title': 'First to Three',
  'lesson.versus-lives.instruction': 'The yellow circles track round wins. Win three rounds to take the match.',
  'lesson.versus-lives.control': 'LEFT CLICK TO CONTINUE',
  'lesson.versus-pass.title': 'Pass To The AI',
  'lesson.versus-pass.instruction': 'Send the ball through center to the AI on the left.',
  'lesson.versus-pass.control': 'LEFT CLICK',
  'lesson.versus-ground.title': 'Clear Ground Hazards',
  'lesson.versus-ground.instruction': 'A low red hazard is coming. Time a power bounce to clear it.',
  'lesson.versus-ground.control': 'RIGHT CLICK',
  'lesson.versus-air.title': 'Respect Air Hazards',
  'lesson.versus-air.instruction': 'Air hazards are dangerous during a power bounce. Stay low and let this one pass.',
  'lesson.versus-air.control': 'AVOID THE AIR HAZARD',
  'lesson.versus-risk.title': 'Risk Cards & Risk Passes',
  'lesson.versus-risk.instruction': 'A dangerous late pass spends a Risk Card. Wait for PASS NOW and make a safe pass.',
  'lesson.versus-risk.control': 'WAIT FOR THE CUE',
  'lesson.versus-recovery.title': 'Recovery Gate',
  'lesson.versus-recovery.instruction': 'Power-bounce through the green card to restore one spent Risk Card.',
  'lesson.versus-recovery.control': 'RIGHT CLICK',
  'lesson.versus-pressure.title': 'Pressure',
  'lesson.versus-pressure.instruction': 'Watch the red hazard accelerate as pressure fills, then pass before it reaches you.',
  'lesson.versus-pressure.control': 'WATCH THE BAR, THEN LEFT CLICK',
  'overlay.paused': 'PAUSED',
  'overlay.pauseSubtitle': 'Take a breath. The court is waiting.',
  'overlay.resume': 'Resume',
  'overlay.restart': 'Restart',
  'overlay.mainMenu': 'Main Menu',
  'power.shop': 'Power-Up Shop',
  'power.inRunBoosts': 'IN-RUN BOOSTS',
  'power.remaining': '{remaining} of {limit} purchases remaining',
  'power.cooldown': 'Next purchase in {seconds}s',
  'power.magnet': 'Coin Magnet',
  'power.magnetDescription': 'Wider coin collection for 12 seconds.',
  'power.shield': 'Shield',
  'power.shieldDescription': 'Invulnerable to hazards for 8 seconds.',
  'power.secondWind': 'Second Wind',
  'power.secondWindDescription': 'Restore one missing heart immediately.',
  'power.buy': 'Buy · {price} Stars',
  'power.active': 'Active',
  'power.healthFull': 'Health Full',
  'power.limitReached': 'Run Limit Reached',
  'power.readyIn': 'Ready in {seconds}s',
  'power.needStars': 'Need {price} Stars',
  'power.courtNotClear': 'Hazard Too Close',
  'overlay.gameOver': 'GAME OVER',
  'overlay.runComplete': 'RUN COMPLETE',
  'overlay.victory': 'VICTORY',
  'overlay.defeat': 'DEFEAT',
  'common.points': 'POINTS',
  'common.currentScore': 'CURRENT SCORE',
  'common.level': 'LEVEL',
  'common.loading': 'Loading',
  'feedback.frenzy': 'STAR POWER - FRENZY!',
  'feedback.newHighScore': 'NEW HIGH SCORE!',
  'feedback.objective': 'OBJECTIVE COMPLETE · +{xp} XP',
  'feedback.allObjectives': 'ALL OBJECTIVES COMPLETE · +{xp} XP · STAR +1',
  'feedback.finalPush': 'FINAL PUSH · 15 SECONDS',
  'feedback.finalPlay': 'FINAL PLAY · RIGHT HAND',
  'feedback.finalShot': 'FINAL SHOT!',
  'feedback.bucket': 'BUCKET! +{points}',
} as const;

type TranslationKey = keyof typeof en;
type Dictionary = Partial<Record<TranslationKey, string>>;

const translations: Readonly<Record<DribbleLanguage, Dictionary>> = {
  en,
  fr: {
    'language.title': 'CHOISISSEZ VOTRE LANGUE',
    'language.subtitle': 'Vous pourrez la modifier dans les paramètres',
    'name.welcome': 'BIENVENUE !',
    'name.subtitle': 'ENTREZ VOTRE NOM POUR COMMENCER',
    'name.placeholder': 'Entrez votre nom...',
    'name.confirm': 'Confirmer',
    'name.error': 'Entrez au moins 2 caractères.',
    'menu.play': 'Jouer', 'menu.achievements': 'Succès', 'menu.tutorial': 'Tutoriel',
    'menu.settings': 'Paramètres', 'menu.shop': 'Boutique', 'menu.exit': 'Quitter',
    'menu.back': 'Retour', 'menu.close': 'Fermer', 'menu.reset': 'Réinitialiser',
    'profile.stars': 'ÉTOILES', 'profile.courtLevel': 'NIVEAU TERRAIN',
    'profile.bestScores': 'MEILLEURS SCORES', 'profile.normal': 'NORMAL', 'profile.hard': 'DIFFICILE',
    'mode.chooseRun': 'CHOISISSEZ VOTRE PARTIE', 'mode.title': 'Mode de jeu',
    'mode.normal': 'Partie normale', 'mode.hard': 'Difficile infini',
    'mode.lastBounce': 'Dernier rebond', 'mode.multiplayer': 'Multijoueur',
    'mode.normalDetail': '3 VIES · 2 MIN · TIR FINAL',
    'mode.hardDetail': '2 VIES · INFINI · SCORE x1,25',
    'mode.comingSoon': 'BIENTÔT', 'mode.online': 'EN LIGNE',
    'tutorial.choose': 'Choisir un tutoriel', 'tutorial.classic': 'Classique',
    'tutorial.classicDetail': 'Cibles, timing, santé et Frénésie',
    'tutorial.versusAi': 'CONTRE IA', 'tutorial.versusDetail': 'Cartes Risque, retours et récupération',
    'settings.title': 'Paramètres', 'settings.language': 'Langue',
    'settings.master': 'Volume principal', 'settings.music': 'Musique', 'settings.sfx': 'Effets sonores',
    'settings.motion': 'Mouvements réduits', 'settings.flashes': 'Flashs réduits',
    'settings.contrast': 'Cibles à contraste élevé', 'settings.touchControls': 'Commandes tactiles',
    'settings.touchSplit': 'Zones tactiles', 'settings.touchSwipe': 'Gestes de balayage',
    'settings.playerData': 'DONNÉES JOUEUR',
    'shop.title': 'Vestiaire', 'shop.complete': 'Collection complète',
    'shop.equipped': 'ÉQUIPÉ', 'shop.owned': 'POSSÉDÉ', 'shop.locked': 'VERROUILLÉ',
    'shop.equip': 'Équiper', 'shop.buy': 'Acheter - {price} étoiles',
    'achievement.score10000.title': 'Partie à cinq chiffres',
    'achievement.score10000.description': 'Marquez 10 000 points en une partie.',
    'achievement.firstPurchase.title': 'Premier achat',
    'achievement.firstPurchase.description': 'Achetez votre premier objet dans la boutique.',
    'achievement.playTutorial.title': 'Journée d’entraînement',
    'achievement.playTutorial.description': 'Terminez les tutoriels Classique et Dernier rebond.',
    'achievement.starWithoutSwitching.title': 'Gardez votre position',
    'achievement.starWithoutSwitching.description': 'Prenez une étoile sans changer de côté.',
    'achievement.highScore.title': 'Meilleur score',
    'achievement.highScore.description': 'Terminez votre première partie et établissez un record.',
    'challenge.scoreSprint.title': 'Sprint de score',
    'challenge.scoreSprint.description': 'Marquez 2 500 points en une partie.',
    'challenge.hazardRun.title': 'Terrain propre',
    'challenge.hazardRun.description': 'Évitez 15 dangers en une partie.',
    'challenge.rallyMaster.title': 'Long échange',
    'challenge.rallyMaster.description': 'Atteignez 12 passes dans Dernier rebond.',
    'challenge.weekly.scoreSprint.title': 'Score hebdomadaire',
    'challenge.weekly.scoreSprint.description': 'Marquez 5 000 points en une partie.',
    'challenge.weekly.hazardRun.title': 'Mur défensif',
    'challenge.weekly.hazardRun.description': 'Évitez 30 dangers en une partie.',
    'challenge.weekly.rallyMaster.title': 'Légende des échanges',
    'challenge.weekly.rallyMaster.description': 'Atteignez 20 passes dans Dernier rebond.',
    'achievements.career': 'PROGRESSION', 'achievements.completeCount': '{count} / {total} TERMINÉS',
    'achievements.complete': 'TERMINÉ', 'achievements.locked': 'VERROUILLÉ',
    'achievements.daily': 'QUOTIDIEN', 'achievements.weekly': 'HEBDOMADAIRE',
    'hud.runObjectives': 'OBJECTIFS', 'hud.allObjectives': 'Tous les objectifs terminés',
    'hud.timeLeft': 'TEMPS RESTANT', 'hud.finalShot': 'TIR FINAL', 'hud.runComplete': 'PARTIE TERMINÉE',
    'hud.frenzy': 'MODE FRÉNÉSIE', 'hud.centerSwitch': 'PASSE AU CENTRE', 'hud.scanning': 'ANALYSE',
    'hud.training': 'ENTRAÎNEMENT {current} / {total}', 'hud.trainingComplete': 'ENTRAÎNEMENT TERMINÉ',
    'hud.exitTutorial': 'QUITTER LE TUTORIEL',
    'objective.score-1200': 'Marquer 1 200', 'objective.score-1800': 'Marquer 1 800',
    'objective.hit-15': 'Toucher 15 cibles', 'objective.perfect-4': '4 passes parfaites',
    'objective.avoid-10': 'Éviter 10 dangers', 'objective.combo-6': 'Atteindre combo x6',
    'objective.survive-45': 'Tenir 45 s', 'objective.star-1': 'Prendre une étoile Frénésie',
    'objective.rounds-2': 'Gagner 2 manches', 'objective.rally-8': 'Échange de 8 passes',
    'objective.returns-7': '7 retours', 'objective.risk-1': '1 passe risquée',
    'objective.versus-45': 'Tenir 45 s',
    'lesson.left-bounce.title': 'Rebond puissant', 'lesson.left-bounce.instruction': 'Le ballon commence à gauche. Envoyez-le au-dessus des dangers bas.', 'lesson.left-bounce.control': 'CLIC GAUCHE',
    'lesson.switch-right.title': 'Changer de main', 'lesson.switch-right.instruction': 'Rebondissez au centre et réceptionnez de la main droite.', 'lesson.switch-right.control': 'CLIC DROIT',
    'lesson.right-bounce.title': 'Rebond puissant droit', 'lesson.right-bounce.instruction': 'Avec le ballon à droite, lancez un nouveau rebond haut.', 'lesson.right-bounce.control': 'CLIC DROIT',
    'lesson.switch-left.title': 'Retour à gauche', 'lesson.switch-left.instruction': 'Repassez par la voie centrale.', 'lesson.switch-left.control': 'CLIC GAUCHE',
    'lesson.score-target.title': 'Cible de score', 'lesson.score-target.instruction': 'Gardez le ballon à gauche pour prendre la cible jaune.', 'lesson.score-target.control': 'GARDEZ VOTRE CÔTÉ',
    'lesson.center-target.title': 'Timing central', 'lesson.center-target.instruction': 'Regardez la jauge. Changez de main quand le marqueur atteint le centre.', 'lesson.center-target.control': 'CLIC DROIT EN RYTHME',
    'lesson.avoid-hazard.title': 'Éviter les dangers', 'lesson.avoid-hazard.instruction': 'La cible rouge coûte une vie. Sautez par-dessus.', 'lesson.avoid-hazard.control': 'REBOND HAUT',
    'lesson.health-target.title': 'Restaurer la vie', 'lesson.health-target.instruction': 'Prenez la croix lumineuse pour restaurer un cœur.', 'lesson.health-target.control': 'GARDEZ VOTRE CÔTÉ',
    'lesson.bonus-star.title': 'Étoile bonus', 'lesson.bonus-star.instruction': 'Les étoiles rares déclenchent la Frénésie. Faites un rebond puissant.', 'lesson.bonus-star.control': 'REBOND HAUT',
    'lesson.frenzy.title': 'Puissance Frénésie', 'lesson.frenzy.instruction': 'Le ballon est doré. En Frénésie, toutes les cibles sont bonnes.', 'lesson.frenzy.control': 'TOUCHEZ LA CIBLE JAUNE',
    'lesson.versus-lives.title': 'Premier à trois', 'lesson.versus-lives.instruction': 'Les cercles jaunes indiquent les manches gagnées. Gagnez trois manches pour remporter le match.', 'lesson.versus-lives.control': 'CLIC GAUCHE POUR CONTINUER',
    'lesson.versus-pass.title': 'Passe à l’IA', 'lesson.versus-pass.instruction': 'Envoyez le ballon au centre vers l’IA à gauche.', 'lesson.versus-pass.control': 'CLIC GAUCHE',
    'lesson.versus-ground.title': 'Dangers au sol', 'lesson.versus-ground.instruction': 'Un danger bas arrive. Faites un rebond puissant au bon moment.', 'lesson.versus-ground.control': 'CLIC DROIT',
    'lesson.versus-air.title': 'Dangers aériens', 'lesson.versus-air.instruction': 'Ils sont dangereux pendant un rebond haut. Restez bas.', 'lesson.versus-air.control': 'ÉVITEZ LE DANGER AÉRIEN',
    'lesson.versus-risk.title': 'Cartes et passes Risque', 'lesson.versus-risk.instruction': 'Une passe tardive dépense une carte. Attendez PASSEZ et jouez prudemment.', 'lesson.versus-risk.control': 'ATTENDEZ LE SIGNAL',
    'lesson.versus-recovery.title': 'Porte de récupération', 'lesson.versus-recovery.instruction': 'Rebondissez dans la carte verte pour récupérer une carte Risque.', 'lesson.versus-recovery.control': 'CLIC DROIT',
    'lesson.versus-pressure.title': 'Pression', 'lesson.versus-pressure.instruction': 'Le danger accélère avec la pression. Passez avant son arrivée.', 'lesson.versus-pressure.control': 'JAUGE, PUIS CLIC GAUCHE',
    'overlay.paused': 'PAUSE', 'overlay.pauseSubtitle': 'Reprenez votre souffle. Le terrain vous attend.',
    'overlay.resume': 'Reprendre', 'overlay.restart': 'Recommencer', 'overlay.mainMenu': 'Menu principal',
    'overlay.gameOver': 'FIN DE PARTIE', 'overlay.runComplete': 'PARTIE TERMINÉE',
    'overlay.victory': 'VICTOIRE', 'overlay.defeat': 'DÉFAITE',
    'common.points': 'POINTS', 'common.currentScore': 'SCORE ACTUEL', 'common.level': 'NIVEAU',
    'common.loading': 'Chargement',
    'feedback.frenzy': 'PUISSANCE ÉTOILE - FRÉNÉSIE !',
    'feedback.newHighScore': 'NOUVEAU RECORD !',
    'feedback.objective': 'OBJECTIF TERMINÉ · +{xp} XP',
    'feedback.allObjectives': 'TOUS LES OBJECTIFS · +{xp} XP · ÉTOILE +1',
    'feedback.finalPush': 'EFFORT FINAL · 15 SECONDES',
    'feedback.finalPlay': 'ACTION FINALE · MAIN DROITE',
    'feedback.finalShot': 'TIR FINAL !', 'feedback.bucket': 'PANIER ! +{points}',
  },
  es: {
    'language.title': 'ELIGE TU IDIOMA', 'language.subtitle': 'Puedes cambiarlo en Ajustes',
    'name.welcome': '¡BIENVENIDO!', 'name.subtitle': 'ESCRIBE TU NOMBRE PARA EMPEZAR',
    'name.placeholder': 'Escribe tu nombre...', 'name.confirm': 'Confirmar',
    'name.error': 'Escribe al menos 2 caracteres.',
    'menu.play': 'Jugar', 'menu.achievements': 'Logros', 'menu.tutorial': 'Tutorial',
    'menu.settings': 'Ajustes', 'menu.shop': 'Tienda', 'menu.exit': 'Salir',
    'menu.back': 'Atrás', 'menu.close': 'Cerrar', 'menu.reset': 'Restablecer datos',
    'profile.stars': 'ESTRELLAS', 'profile.courtLevel': 'NIVEL DE CANCHA',
    'profile.bestScores': 'MEJORES PUNTOS', 'profile.normal': 'NORMAL', 'profile.hard': 'DIFÍCIL',
    'mode.chooseRun': 'ELIGE TU PARTIDA', 'mode.title': 'Modo de juego',
    'mode.normal': 'Partida normal', 'mode.hard': 'Difícil infinito',
    'mode.lastBounce': 'Último rebote', 'mode.multiplayer': 'Multijugador',
    'mode.normalDetail': '3 VIDAS · 2 MIN · TIRO FINAL', 'mode.hardDetail': '2 VIDAS · INFINITO · PUNTOS x1,25',
    'mode.comingSoon': 'PRÓXIMAMENTE', 'mode.online': 'EN LÍNEA',
    'tutorial.choose': 'Elige tutorial', 'tutorial.classic': 'Clásico',
    'tutorial.classicDetail': 'Objetivos, ritmo, salud y Frenesí',
    'tutorial.versusAi': 'CONTRA IA', 'tutorial.versusDetail': 'Cartas de riesgo, devoluciones y recuperación',
    'settings.title': 'Ajustes', 'settings.language': 'Idioma', 'settings.master': 'Volumen general',
    'settings.music': 'Música', 'settings.sfx': 'Efectos de sonido', 'settings.motion': 'Movimiento reducido',
    'settings.flashes': 'Destellos reducidos', 'settings.contrast': 'Objetivos de alto contraste',
    'settings.touchControls': 'Controles táctiles', 'settings.touchSplit': 'Toque dividido',
    'settings.touchSwipe': 'Gestos de deslizamiento',
    'settings.playerData': 'DATOS DEL JUGADOR',
    'shop.title': 'Vestuario', 'shop.complete': 'Colección completa', 'shop.equipped': 'EQUIPADO',
    'shop.owned': 'OBTENIDO', 'shop.locked': 'BLOQUEADO', 'shop.equip': 'Equipar',
    'shop.buy': 'Comprar - {price} estrellas',
    'achievement.score10000.title': 'Partida de cinco cifras',
    'achievement.score10000.description': 'Consigue 10.000 puntos en una partida.',
    'achievement.firstPurchase.title': 'Primera compra',
    'achievement.firstPurchase.description': 'Compra tu primer artículo en la tienda.',
    'achievement.playTutorial.title': 'Día de entrenamiento',
    'achievement.playTutorial.description': 'Completa los tutoriales Clásico y Último rebote.',
    'achievement.starWithoutSwitching.title': 'Mantén tu posición',
    'achievement.starWithoutSwitching.description': 'Recoge una estrella sin cambiar de lado.',
    'achievement.highScore.title': 'Récord',
    'achievement.highScore.description': 'Completa tu primera partida y establece un récord.',
    'challenge.scoreSprint.title': 'Sprint de puntos',
    'challenge.scoreSprint.description': 'Consigue 2.500 puntos en una partida.',
    'challenge.hazardRun.title': 'Cancha limpia',
    'challenge.hazardRun.description': 'Evita 15 peligros en una partida.',
    'challenge.rallyMaster.title': 'Rally largo',
    'challenge.rallyMaster.description': 'Alcanza 12 pases en Último rebote.',
    'challenge.weekly.scoreSprint.title': 'Anotador semanal',
    'challenge.weekly.scoreSprint.description': 'Consigue 5.000 puntos en una partida.',
    'challenge.weekly.hazardRun.title': 'Muro defensivo',
    'challenge.weekly.hazardRun.description': 'Evita 30 peligros en una partida.',
    'challenge.weekly.rallyMaster.title': 'Leyenda del rally',
    'challenge.weekly.rallyMaster.description': 'Alcanza 20 pases en Último rebote.',
    'achievements.career': 'PROGRESO', 'achievements.completeCount': '{count} / {total} COMPLETADOS',
    'achievements.complete': 'COMPLETADO', 'achievements.locked': 'BLOQUEADO',
    'achievements.daily': 'DIARIO', 'achievements.weekly': 'SEMANAL',
    'hud.runObjectives': 'OBJETIVOS', 'hud.allObjectives': 'Todos los objetivos completados',
    'hud.timeLeft': 'TIEMPO RESTANTE', 'hud.finalShot': 'TIRO FINAL', 'hud.runComplete': 'PARTIDA COMPLETADA',
    'hud.frenzy': 'MODO FRENESÍ', 'hud.centerSwitch': 'CAMBIO CENTRAL', 'hud.scanning': 'ANALIZANDO',
    'hud.training': 'ENTRENAMIENTO {current} / {total}', 'hud.trainingComplete': 'ENTRENAMIENTO COMPLETADO',
    'hud.exitTutorial': 'SALIR DEL TUTORIAL',
    'objective.score-1200': 'Consigue 1.200', 'objective.score-1800': 'Consigue 1.800',
    'objective.hit-15': 'Golpea 15 objetivos', 'objective.perfect-4': '4 cambios perfectos',
    'objective.avoid-10': 'Evita 10 peligros', 'objective.combo-6': 'Alcanza combo x6',
    'objective.survive-45': 'Aguanta 45 s', 'objective.star-1': 'Recoge estrella Frenesí',
    'objective.rounds-2': 'Gana 2 rondas', 'objective.rally-8': 'Rally de 8 pases',
    'objective.returns-7': '7 devoluciones', 'objective.risk-1': '1 pase arriesgado',
    'objective.versus-45': 'Mantén el rally 45 s',
    'lesson.left-bounce.title': 'Rebote potente', 'lesson.left-bounce.instruction': 'El balón empieza a la izquierda. Lánzalo sobre los peligros bajos.', 'lesson.left-bounce.control': 'CLIC IZQUIERDO',
    'lesson.switch-right.title': 'Cambiar de mano', 'lesson.switch-right.instruction': 'Rebota por el centro y recibe con la mano derecha.', 'lesson.switch-right.control': 'CLIC DERECHO',
    'lesson.right-bounce.title': 'Rebote potente derecho', 'lesson.right-bounce.instruction': 'Con el balón a la derecha, lanza otro rebote alto.', 'lesson.right-bounce.control': 'CLIC DERECHO',
    'lesson.switch-left.title': 'Volver a la izquierda', 'lesson.switch-left.instruction': 'Cambia por el carril central.', 'lesson.switch-left.control': 'CLIC IZQUIERDO',
    'lesson.score-target.title': 'Objetivo de puntos', 'lesson.score-target.instruction': 'Mantén el balón a la izquierda para recoger el objetivo amarillo.', 'lesson.score-target.control': 'MANTÉN TU LADO',
    'lesson.center-target.title': 'Ritmo central', 'lesson.center-target.instruction': 'Mira el medidor. Cambia cuando el marcador llegue al centro.', 'lesson.center-target.control': 'CLIC DERECHO A RITMO',
    'lesson.avoid-hazard.title': 'Evita peligros', 'lesson.avoid-hazard.instruction': 'El objetivo rojo cuesta una vida. Salta por encima.', 'lesson.avoid-hazard.control': 'REBOTE ALTO',
    'lesson.health-target.title': 'Recupera vida', 'lesson.health-target.instruction': 'Recoge la cruz brillante para recuperar un corazón.', 'lesson.health-target.control': 'MANTÉN TU LADO',
    'lesson.bonus-star.title': 'Estrella extra', 'lesson.bonus-star.instruction': 'Las estrellas raras activan Frenesí. Usa un rebote potente.', 'lesson.bonus-star.control': 'REBOTE ALTO',
    'lesson.frenzy.title': 'Poder Frenesí', 'lesson.frenzy.instruction': 'El balón se volvió dorado. En Frenesí, todos los objetivos son buenos.', 'lesson.frenzy.control': 'GOLPEA EL OBJETIVO AMARILLO',
    'lesson.versus-lives.title': 'Primero a tres', 'lesson.versus-lives.instruction': 'Los círculos amarillos indican las rondas ganadas. Gana tres rondas para vencer.', 'lesson.versus-lives.control': 'CLIC IZQUIERDO PARA SEGUIR',
    'lesson.versus-pass.title': 'Pasa a la IA', 'lesson.versus-pass.instruction': 'Envía el balón por el centro a la IA izquierda.', 'lesson.versus-pass.control': 'CLIC IZQUIERDO',
    'lesson.versus-ground.title': 'Peligros de suelo', 'lesson.versus-ground.instruction': 'Viene un peligro bajo. Usa un rebote potente a tiempo.', 'lesson.versus-ground.control': 'CLIC DERECHO',
    'lesson.versus-air.title': 'Peligros aéreos', 'lesson.versus-air.instruction': 'Son peligrosos durante un rebote alto. Mantente abajo.', 'lesson.versus-air.control': 'EVITA EL PELIGRO AÉREO',
    'lesson.versus-risk.title': 'Cartas y pases de riesgo', 'lesson.versus-risk.instruction': 'Un pase tardío gasta una carta. Espera PASA AHORA y juega seguro.', 'lesson.versus-risk.control': 'ESPERA LA SEÑAL',
    'lesson.versus-recovery.title': 'Puerta de recuperación', 'lesson.versus-recovery.instruction': 'Rebota por la carta verde para recuperar una carta de riesgo.', 'lesson.versus-recovery.control': 'CLIC DERECHO',
    'lesson.versus-pressure.title': 'Presión', 'lesson.versus-pressure.instruction': 'El peligro acelera al llenarse la presión. Pasa antes de que llegue.', 'lesson.versus-pressure.control': 'MIRA LA BARRA Y HAZ CLIC',
    'overlay.paused': 'PAUSA', 'overlay.pauseSubtitle': 'Respira. La cancha te espera.',
    'overlay.resume': 'Continuar', 'overlay.restart': 'Reiniciar', 'overlay.mainMenu': 'Menú principal',
    'overlay.gameOver': 'FIN DE PARTIDA', 'overlay.runComplete': 'PARTIDA COMPLETADA',
    'overlay.victory': 'VICTORIA', 'overlay.defeat': 'DERROTA',
    'common.points': 'PUNTOS', 'common.currentScore': 'PUNTUACIÓN ACTUAL', 'common.level': 'NIVEL',
    'common.loading': 'Cargando',
    'feedback.frenzy': '¡PODER ESTRELLA - FRENESÍ!', 'feedback.newHighScore': '¡NUEVO RÉCORD!',
    'feedback.objective': 'OBJETIVO COMPLETADO · +{xp} XP',
    'feedback.allObjectives': 'TODOS LOS OBJETIVOS · +{xp} XP · ESTRELLA +1',
    'feedback.finalPush': 'TRAMO FINAL · 15 SEGUNDOS',
    'feedback.finalPlay': 'JUGADA FINAL · MANO DERECHA',
    'feedback.finalShot': '¡TIRO FINAL!', 'feedback.bucket': '¡CANASTA! +{points}',
  },
  de: {
    'language.title': 'SPRACHE WÄHLEN', 'language.subtitle': 'Später in den Einstellungen änderbar',
    'name.welcome': 'WILLKOMMEN!', 'name.subtitle': 'GIB DEINEN NAMEN EIN',
    'name.placeholder': 'Namen eingeben...', 'name.confirm': 'Bestätigen',
    'name.error': 'Gib mindestens 2 Zeichen ein.',
    'menu.play': 'Spielen', 'menu.achievements': 'Erfolge', 'menu.tutorial': 'Training',
    'menu.settings': 'Einstellungen', 'menu.shop': 'Shop', 'menu.exit': 'Beenden',
    'menu.back': 'Zurück', 'menu.close': 'Schließen', 'menu.reset': 'Daten zurücksetzen',
    'profile.stars': 'STERNE', 'profile.courtLevel': 'COURT-LEVEL',
    'profile.bestScores': 'BESTWERTE', 'profile.normal': 'NORMAL', 'profile.hard': 'SCHWER',
    'mode.chooseRun': 'RUN AUSWÄHLEN', 'mode.title': 'Spielmodus',
    'mode.normal': 'Normaler Run', 'mode.hard': 'Endlos schwer',
    'mode.lastBounce': 'Letzter Bounce', 'mode.multiplayer': 'Mehrspieler',
    'mode.normalDetail': '3 LEBEN · 2 MIN · FINALWURF', 'mode.hardDetail': '2 LEBEN · ENDLOS · PUNKTE x1,25',
    'mode.comingSoon': 'BALD VERFÜGBAR', 'mode.online': 'ONLINE',
    'tutorial.choose': 'Training wählen', 'tutorial.classic': 'Klassisch',
    'tutorial.classicDetail': 'Ziele, Timing, Gesundheit und Frenzy',
    'tutorial.versusAi': 'GEGEN KI', 'tutorial.versusDetail': 'Risikokarten, Rückgaben und Erholung',
    'settings.title': 'Einstellungen', 'settings.language': 'Sprache', 'settings.master': 'Gesamtlautstärke',
    'settings.music': 'Musik', 'settings.sfx': 'Soundeffekte', 'settings.motion': 'Weniger Bewegung',
    'settings.flashes': 'Weniger Blitze', 'settings.contrast': 'Hoher Zielkontrast',
    'settings.touchControls': 'Touch-Steuerung', 'settings.touchSplit': 'Geteiltes Tippen',
    'settings.touchSwipe': 'Wischgesten',
    'settings.playerData': 'SPIELERDATEN',
    'shop.title': 'Spind', 'shop.complete': 'Sammlung vollständig', 'shop.equipped': 'AUSGERÜSTET',
    'shop.owned': 'IM BESITZ', 'shop.locked': 'GESPERRT', 'shop.equip': 'Ausrüsten',
    'shop.buy': 'Kaufen - {price} Sterne',
    'achievement.score10000.title': 'Fünfstelliger Run',
    'achievement.score10000.description': 'Erziele 10.000 Punkte in einem Spiel.',
    'achievement.firstPurchase.title': 'Erster Kauf',
    'achievement.firstPurchase.description': 'Kaufe deinen ersten Gegenstand im Shop.',
    'achievement.playTutorial.title': 'Trainingstag',
    'achievement.playTutorial.description': 'Schließe beide Trainings ab.',
    'achievement.starWithoutSwitching.title': 'Position halten',
    'achievement.starWithoutSwitching.description': 'Sammle einen Stern ohne Seitenwechsel.',
    'achievement.highScore.title': 'Bestwert',
    'achievement.highScore.description': 'Beende deinen ersten Run und stelle einen Rekord auf.',
    'challenge.scoreSprint.title': 'Punkte-Sprint',
    'challenge.scoreSprint.description': 'Erziele 2.500 Punkte in einem Run.',
    'challenge.hazardRun.title': 'Sauberer Court',
    'challenge.hazardRun.description': 'Weiche 15 Gefahren in einem Run aus.',
    'challenge.rallyMaster.title': 'Lange Rally',
    'challenge.rallyMaster.description': 'Erreiche 12 Pässe in Letzter Bounce.',
    'challenge.weekly.scoreSprint.title': 'Wochenwertung',
    'challenge.weekly.scoreSprint.description': 'Erziele 5.000 Punkte in einem Run.',
    'challenge.weekly.hazardRun.title': 'Defensivwand',
    'challenge.weekly.hazardRun.description': 'Weiche 30 Gefahren in einem Run aus.',
    'challenge.weekly.rallyMaster.title': 'Rally-Legende',
    'challenge.weekly.rallyMaster.description': 'Erreiche 20 Pässe in Letzter Bounce.',
    'achievements.career': 'KARRIEREFORTSCHRITT', 'achievements.completeCount': '{count} / {total} FERTIG',
    'achievements.complete': 'FERTIG', 'achievements.locked': 'GESPERRT',
    'achievements.daily': 'TÄGLICH', 'achievements.weekly': 'WÖCHENTLICH',
    'hud.runObjectives': 'RUN-ZIELE', 'hud.allObjectives': 'Alle Ziele abgeschlossen',
    'hud.timeLeft': 'RESTZEIT', 'hud.finalShot': 'FINALWURF', 'hud.runComplete': 'RUN BEENDET',
    'hud.frenzy': 'FRENZY-MODUS', 'hud.centerSwitch': 'MITTENWECHSEL', 'hud.scanning': 'SCANNEN',
    'hud.training': 'TRAINING {current} / {total}', 'hud.trainingComplete': 'TRAINING BEENDET',
    'hud.exitTutorial': 'TRAINING VERLASSEN',
    'objective.score-1200': '1.200 Punkte', 'objective.score-1800': '1.800 Punkte',
    'objective.hit-15': '15 Ziele treffen', 'objective.perfect-4': '4 perfekte Wechsel',
    'objective.avoid-10': '10 Gefahren meiden', 'objective.combo-6': 'Combo x6 erreichen',
    'objective.survive-45': '45 Sek. durchhalten', 'objective.star-1': 'Frenzy-Stern sammeln',
    'objective.rounds-2': '2 Runden gewinnen', 'objective.rally-8': '8-Pass-Rally',
    'objective.returns-7': '7 Rückgaben', 'objective.risk-1': '1 Risikopass',
    'objective.versus-45': 'Rally 45 Sek. halten',
    'lesson.left-bounce.title': 'Power-Bounce', 'lesson.left-bounce.instruction': 'Der Ball startet links. Schicke ihn über niedrige Gefahren.', 'lesson.left-bounce.control': 'LINKSKLICK',
    'lesson.switch-right.title': 'Hand wechseln', 'lesson.switch-right.instruction': 'Prelle durch die Mitte und fange rechts.', 'lesson.switch-right.control': 'RECHTSKLICK',
    'lesson.right-bounce.title': 'Rechter Power-Bounce', 'lesson.right-bounce.instruction': 'Starte rechts einen weiteren hohen Bounce.', 'lesson.right-bounce.control': 'RECHTSKLICK',
    'lesson.switch-left.title': 'Zurück nach links', 'lesson.switch-left.instruction': 'Wechsle durch die Mittelspur zurück.', 'lesson.switch-left.control': 'LINKSKLICK',
    'lesson.score-target.title': 'Punkteziel', 'lesson.score-target.instruction': 'Halte den Ball links, um das gelbe Ziel zu treffen.', 'lesson.score-target.control': 'SPUR HALTEN',
    'lesson.center-target.title': 'Mittel-Timing', 'lesson.center-target.instruction': 'Beobachte die Anzeige. Wechsle in der Mitte.', 'lesson.center-target.control': 'RECHTSKLICK IM TAKT',
    'lesson.avoid-hazard.title': 'Gefahren meiden', 'lesson.avoid-hazard.instruction': 'Das rote Ziel kostet ein Leben. Springe darüber.', 'lesson.avoid-hazard.control': 'HOHER BOUNCE',
    'lesson.health-target.title': 'Leben auffüllen', 'lesson.health-target.instruction': 'Sammle das leuchtende Kreuz für ein Herz.', 'lesson.health-target.control': 'SPUR HALTEN',
    'lesson.bonus-star.title': 'Bonus-Stern', 'lesson.bonus-star.instruction': 'Seltene Sterne starten Frenzy. Nutze einen Power-Bounce.', 'lesson.bonus-star.control': 'HOHER BOUNCE',
    'lesson.frenzy.title': 'Frenzy-Power', 'lesson.frenzy.instruction': 'Der Ball ist golden. In Frenzy sind alle Ziele gut.', 'lesson.frenzy.control': 'GELBES ZIEL TREFFEN',
    'lesson.versus-lives.title': 'Drei Rundensiege', 'lesson.versus-lives.instruction': 'Die gelben Kreise zeigen Rundensiege. Gewinne drei Runden und damit das Match.', 'lesson.versus-lives.control': 'LINKSKLICK ZUM FORTFAHREN',
    'lesson.versus-pass.title': 'Pass zur KI', 'lesson.versus-pass.instruction': 'Schicke den Ball durch die Mitte zur linken KI.', 'lesson.versus-pass.control': 'LINKSKLICK',
    'lesson.versus-ground.title': 'Bodengefahren', 'lesson.versus-ground.instruction': 'Eine niedrige Gefahr kommt. Springe rechtzeitig darüber.', 'lesson.versus-ground.control': 'RECHTSKLICK',
    'lesson.versus-air.title': 'Luftgefahren', 'lesson.versus-air.instruction': 'Sie sind beim hohen Bounce gefährlich. Bleibe unten.', 'lesson.versus-air.control': 'LUFTGEFAHR MEIDEN',
    'lesson.versus-risk.title': 'Risikokarten und -pässe', 'lesson.versus-risk.instruction': 'Ein später Pass kostet eine Karte. Warte auf JETZT PASSEN.', 'lesson.versus-risk.control': 'AUF SIGNAL WARTEN',
    'lesson.versus-recovery.title': 'Erholungstor', 'lesson.versus-recovery.instruction': 'Springe durch die grüne Karte, um eine Risikokarte zurückzuholen.', 'lesson.versus-recovery.control': 'RECHTSKLICK',
    'lesson.versus-pressure.title': 'Druck', 'lesson.versus-pressure.instruction': 'Die Gefahr beschleunigt mit dem Druck. Passe rechtzeitig.', 'lesson.versus-pressure.control': 'ANZEIGE, DANN LINKSKLICK',
    'overlay.paused': 'PAUSE', 'overlay.pauseSubtitle': 'Hol Luft. Der Court wartet.',
    'overlay.resume': 'Fortsetzen', 'overlay.restart': 'Neustart', 'overlay.mainMenu': 'Hauptmenü',
    'overlay.gameOver': 'GAME OVER', 'overlay.runComplete': 'RUN BEENDET',
    'overlay.victory': 'SIEG', 'overlay.defeat': 'NIEDERLAGE',
    'common.points': 'PUNKTE', 'common.currentScore': 'AKTUELLER PUNKTSTAND', 'common.level': 'LEVEL',
    'common.loading': 'Laden',
    'feedback.frenzy': 'STERNPOWER - FRENZY!', 'feedback.newHighScore': 'NEUER BESTWERT!',
    'feedback.objective': 'ZIEL ERREICHT · +{xp} XP',
    'feedback.allObjectives': 'ALLE ZIELE · +{xp} XP · STERN +1',
    'feedback.finalPush': 'ENDSPURT · 15 SEKUNDEN',
    'feedback.finalPlay': 'FINALER SPIELZUG · RECHTE HAND',
    'feedback.finalShot': 'FINALWURF!', 'feedback.bucket': 'TREFFER! +{points}',
  },
  'pt-BR': {
    'language.title': 'ESCOLHA SEU IDIOMA', 'language.subtitle': 'Você pode alterar nos Ajustes',
    'name.welcome': 'BEM-VINDO!', 'name.subtitle': 'DIGITE SEU NOME PARA COMEÇAR',
    'name.placeholder': 'Digite seu nome...', 'name.confirm': 'Confirmar',
    'name.error': 'Digite pelo menos 2 caracteres.',
    'menu.play': 'Jogar', 'menu.achievements': 'Conquistas', 'menu.tutorial': 'Tutorial',
    'menu.settings': 'Ajustes', 'menu.shop': 'Loja', 'menu.exit': 'Sair',
    'menu.back': 'Voltar', 'menu.close': 'Fechar', 'menu.reset': 'Redefinir dados',
    'profile.stars': 'ESTRELAS', 'profile.courtLevel': 'NÍVEL DA QUADRA',
    'profile.bestScores': 'MELHORES PONTOS', 'profile.normal': 'NORMAL', 'profile.hard': 'DIFÍCIL',
    'mode.chooseRun': 'ESCOLHA SUA PARTIDA', 'mode.title': 'Modo de jogo',
    'mode.normal': 'Partida normal', 'mode.hard': 'Difícil infinito',
    'mode.lastBounce': 'Último quique', 'mode.multiplayer': 'Multijogador',
    'mode.normalDetail': '3 VIDAS · 2 MIN · ARREMESSO FINAL',
    'mode.hardDetail': '2 VIDAS · INFINITO · PONTOS x1,25',
    'mode.comingSoon': 'EM BREVE', 'mode.online': 'ONLINE',
    'tutorial.choose': 'Escolha o tutorial', 'tutorial.classic': 'Clássico',
    'tutorial.classicDetail': 'Alvos, ritmo, vida e Frenesi',
    'tutorial.versusAi': 'CONTRA IA', 'tutorial.versusDetail': 'Cartas de risco, devoluções e recuperação',
    'settings.title': 'Ajustes', 'settings.language': 'Idioma', 'settings.master': 'Volume geral',
    'settings.music': 'Música', 'settings.sfx': 'Efeitos sonoros', 'settings.motion': 'Movimento reduzido',
    'settings.flashes': 'Flashes reduzidos', 'settings.contrast': 'Alvos de alto contraste',
    'settings.touchControls': 'Controles de toque', 'settings.touchSplit': 'Toque dividido',
    'settings.touchSwipe': 'Gestos de deslizar',
    'settings.playerData': 'DADOS DO JOGADOR',
    'shop.title': 'Armário', 'shop.complete': 'Coleção completa', 'shop.equipped': 'EQUIPADO',
    'shop.owned': 'ADQUIRIDO', 'shop.locked': 'BLOQUEADO', 'shop.equip': 'Equipar',
    'shop.buy': 'Comprar - {price} estrelas',
    'achievement.score10000.title': 'Partida de cinco dígitos',
    'achievement.score10000.description': 'Marque 10.000 pontos em uma partida.',
    'achievement.firstPurchase.title': 'Primeira compra',
    'achievement.firstPurchase.description': 'Compre seu primeiro item na loja.',
    'achievement.playTutorial.title': 'Dia de treino',
    'achievement.playTutorial.description': 'Conclua os tutoriais Clássico e Último quique.',
    'achievement.starWithoutSwitching.title': 'Mantenha a posição',
    'achievement.starWithoutSwitching.description': 'Pegue uma estrela sem trocar de lado.',
    'achievement.highScore.title': 'Recorde',
    'achievement.highScore.description': 'Conclua sua primeira partida e estabeleça um recorde.',
    'challenge.scoreSprint.title': 'Sprint de pontos',
    'challenge.scoreSprint.description': 'Marque 2.500 pontos em uma partida.',
    'challenge.hazardRun.title': 'Quadra limpa',
    'challenge.hazardRun.description': 'Evite 15 perigos em uma partida.',
    'challenge.rallyMaster.title': 'Rali longo',
    'challenge.rallyMaster.description': 'Alcance 12 passes no Último quique.',
    'challenge.weekly.scoreSprint.title': 'Pontuador semanal',
    'challenge.weekly.scoreSprint.description': 'Marque 5.000 pontos em uma partida.',
    'challenge.weekly.hazardRun.title': 'Muralha defensiva',
    'challenge.weekly.hazardRun.description': 'Evite 30 perigos em uma partida.',
    'challenge.weekly.rallyMaster.title': 'Lenda do rali',
    'challenge.weekly.rallyMaster.description': 'Alcance 20 passes no Último quique.',
    'achievements.career': 'PROGRESSO', 'achievements.completeCount': '{count} / {total} CONCLUÍDOS',
    'achievements.complete': 'CONCLUÍDO', 'achievements.locked': 'BLOQUEADO',
    'achievements.daily': 'DIÁRIO', 'achievements.weekly': 'SEMANAL',
    'hud.runObjectives': 'OBJETIVOS', 'hud.allObjectives': 'Todos os objetivos concluídos',
    'hud.timeLeft': 'TEMPO RESTANTE', 'hud.finalShot': 'ARREMESSO FINAL', 'hud.runComplete': 'PARTIDA CONCLUÍDA',
    'hud.frenzy': 'MODO FRENESI', 'hud.centerSwitch': 'TROCA CENTRAL', 'hud.scanning': 'ANALISANDO',
    'hud.training': 'TREINO {current} / {total}', 'hud.trainingComplete': 'TREINO CONCLUÍDO',
    'hud.exitTutorial': 'SAIR DO TUTORIAL',
    'objective.score-1200': 'Marque 1.200', 'objective.score-1800': 'Marque 1.800',
    'objective.hit-15': 'Acerte 15 alvos', 'objective.perfect-4': '4 trocas perfeitas',
    'objective.avoid-10': 'Evite 10 perigos', 'objective.combo-6': 'Alcance combo x6',
    'objective.survive-45': 'Sobreviva 45 s', 'objective.star-1': 'Pegue estrela Frenesi',
    'objective.rounds-2': 'Vença 2 rodadas', 'objective.rally-8': 'Rali de 8 passes',
    'objective.returns-7': '7 devoluções', 'objective.risk-1': '1 passe arriscado',
    'objective.versus-45': 'Mantenha o rali 45 s',
    'lesson.left-bounce.title': 'Quique potente', 'lesson.left-bounce.instruction': 'A bola começa à esquerda. Lance acima dos perigos baixos.', 'lesson.left-bounce.control': 'CLIQUE ESQUERDO',
    'lesson.switch-right.title': 'Trocar de mão', 'lesson.switch-right.instruction': 'Quique pelo centro e receba com a mão direita.', 'lesson.switch-right.control': 'CLIQUE DIREITO',
    'lesson.right-bounce.title': 'Quique potente direito', 'lesson.right-bounce.instruction': 'Com a bola à direita, lance outro quique alto.', 'lesson.right-bounce.control': 'CLIQUE DIREITO',
    'lesson.switch-left.title': 'Voltar à esquerda', 'lesson.switch-left.instruction': 'Troque de volta pela faixa central.', 'lesson.switch-left.control': 'CLIQUE ESQUERDO',
    'lesson.score-target.title': 'Alvo de pontos', 'lesson.score-target.instruction': 'Mantenha a bola à esquerda para pegar o alvo amarelo.', 'lesson.score-target.control': 'MANTENHA SEU LADO',
    'lesson.center-target.title': 'Ritmo central', 'lesson.center-target.instruction': 'Observe o medidor. Troque quando o marcador chegar ao centro.', 'lesson.center-target.control': 'CLIQUE DIREITO NO RITMO',
    'lesson.avoid-hazard.title': 'Evite perigos', 'lesson.avoid-hazard.instruction': 'O alvo vermelho custa uma vida. Salte por cima.', 'lesson.avoid-hazard.control': 'QUIQUE ALTO',
    'lesson.health-target.title': 'Recupere vida', 'lesson.health-target.instruction': 'Pegue a cruz brilhante para recuperar um coração.', 'lesson.health-target.control': 'MANTENHA SEU LADO',
    'lesson.bonus-star.title': 'Estrela bônus', 'lesson.bonus-star.instruction': 'Estrelas raras ativam Frenesi. Use um quique potente.', 'lesson.bonus-star.control': 'QUIQUE ALTO',
    'lesson.frenzy.title': 'Poder Frenesi', 'lesson.frenzy.instruction': 'A bola ficou dourada. No Frenesi, todos os alvos são bons.', 'lesson.frenzy.control': 'ACERTE O ALVO AMARELO',
    'lesson.versus-lives.title': 'Primeiro a três', 'lesson.versus-lives.instruction': 'Os círculos amarelos mostram vitórias em rodadas. Vença três rodadas para ganhar a partida.', 'lesson.versus-lives.control': 'CLIQUE ESQUERDO PARA CONTINUAR',
    'lesson.versus-pass.title': 'Passe para a IA', 'lesson.versus-pass.instruction': 'Envie a bola pelo centro para a IA à esquerda.', 'lesson.versus-pass.control': 'CLIQUE ESQUERDO',
    'lesson.versus-ground.title': 'Perigos no chão', 'lesson.versus-ground.instruction': 'Um perigo baixo está vindo. Use o quique potente na hora certa.', 'lesson.versus-ground.control': 'CLIQUE DIREITO',
    'lesson.versus-air.title': 'Perigos no ar', 'lesson.versus-air.instruction': 'Eles são perigosos no quique alto. Fique baixo.', 'lesson.versus-air.control': 'EVITE O PERIGO AÉREO',
    'lesson.versus-risk.title': 'Cartas e passes de risco', 'lesson.versus-risk.instruction': 'Um passe tardio gasta uma carta. Espere PASSE AGORA.', 'lesson.versus-risk.control': 'ESPERE O SINAL',
    'lesson.versus-recovery.title': 'Portal de recuperação', 'lesson.versus-recovery.instruction': 'Quique pela carta verde para recuperar uma Carta de Risco.', 'lesson.versus-recovery.control': 'CLIQUE DIREITO',
    'lesson.versus-pressure.title': 'Pressão', 'lesson.versus-pressure.instruction': 'O perigo acelera com a pressão. Passe antes que ele chegue.', 'lesson.versus-pressure.control': 'OLHE A BARRA E CLIQUE',
    'overlay.paused': 'PAUSADO', 'overlay.pauseSubtitle': 'Respire. A quadra está esperando.',
    'overlay.resume': 'Continuar', 'overlay.restart': 'Reiniciar', 'overlay.mainMenu': 'Menu principal',
    'overlay.gameOver': 'FIM DE JOGO', 'overlay.runComplete': 'PARTIDA CONCLUÍDA',
    'overlay.victory': 'VITÓRIA', 'overlay.defeat': 'DERROTA',
    'common.points': 'PONTOS', 'common.currentScore': 'PONTUAÇÃO ATUAL', 'common.level': 'NÍVEL',
    'common.loading': 'Carregando',
    'feedback.frenzy': 'PODER DA ESTRELA - FRENESI!', 'feedback.newHighScore': 'NOVO RECORDE!',
    'feedback.objective': 'OBJETIVO CONCLUÍDO · +{xp} XP',
    'feedback.allObjectives': 'TODOS OS OBJETIVOS · +{xp} XP · ESTRELA +1',
    'feedback.finalPush': 'RETA FINAL · 15 SEGUNDOS',
    'feedback.finalPlay': 'JOGADA FINAL · MÃO DIREITA',
    'feedback.finalShot': 'ARREMESSO FINAL!', 'feedback.bucket': 'CESTA! +{points}',
  },
};

const listeners = new Set<(language: DribbleLanguage) => void>();

function isLanguage(value: unknown): value is DribbleLanguage {
  return typeof value === 'string' && supportedLanguages.includes(value as DribbleLanguage);
}

export function loadSavedLanguage(): DribbleLanguage | null {
  try {
    const stored = localStorage.getItem(languageStorageKey);
    return isLanguage(stored) ? stored : null;
  } catch {
    return null;
  }
}

export function detectLanguage(): DribbleLanguage {
  const locale = typeof navigator === 'undefined' ? 'en' : navigator.language;
  const normalized = locale.toLowerCase();
  if (normalized.startsWith('fr')) return 'fr';
  if (normalized.startsWith('es')) return 'es';
  if (normalized.startsWith('de')) return 'de';
  if (normalized.startsWith('pt')) return 'pt-BR';
  return 'en';
}

let currentLanguage: DribbleLanguage = loadSavedLanguage() ?? detectLanguage();

export function getLanguage(): DribbleLanguage {
  return currentLanguage;
}

export function setLanguage(language: DribbleLanguage, persist = true): void {
  currentLanguage = language;
  if (persist) {
    try {
      localStorage.setItem(languageStorageKey, language);
    } catch {
      // The language remains active for this session when storage is unavailable.
    }
  }
  document.documentElement.lang = language;
  for (const listener of listeners) listener(language);
}

export function clearSavedLanguage(): void {
  try {
    localStorage.removeItem(languageStorageKey);
  } catch {
    // A fresh language selection will still be requested when storage is available again.
  }
}

export function onLanguageChanged(listener: (language: DribbleLanguage) => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function t(key: TranslationKey, params?: TranslationParams): string {
  let value = translations[currentLanguage][key] ?? en[key];
  if (!params) return value;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

export type { TranslationKey };
