// This file is auto-generated by scripts/generate-property-metadata.ts
// Do not edit manually

import { registerGeneratedClassMetadata, registerGeneratedPropertyMetadata } from '@gnsx/genesys.js';

import { DynamicUVNodeMaterialAsset } from './dynamic-uv-material.js';

export function registerMetadata(): void {
  registerGeneratedClassMetadata(DynamicUVNodeMaterialAsset, { description: "World-space triplanar material. Samples the texture three times using\nworld-position XZ, XY, and YZ planes, then blends by the world normal —\nno per-mesh UV coordinates required." });
  registerGeneratedPropertyMetadata(DynamicUVNodeMaterialAsset, {
      "mapPath": {
        "type": "texturePath",
        "description": "Base color texture"
      },
      "scale": {
        "type": "number",
        "min": 0.01,
        "max": 20,
        "step": 0.01,
        "description": "Texture scale in world units"
      },
      "color": {
        "type": "color",
        "description": "Tint color"
      },
      "roughness": {
        "type": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Roughness"
      },
      "metalness": {
        "type": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Metalness"
      }
    });

}

// Deferred to avoid circular reference issues during module initialization
queueMicrotask(registerMetadata);
